# Generated by Django 2.1.5 on 2020-02-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_favoriteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
