# Generated by Django 2.1.5 on 2020-02-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='star',
            field=models.BooleanField(),
        ),
    ]
